[package]
name = "revive-builtins"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[features]
riscv-64 = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
