[package]
name = "revive-benchmarks"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
authors.workspace = true
description = "revive compiler benchmarks"

[features]
default = ["bench-pvm-interpreter"]
bench-pvm-interpreter = []
bench-pvm = []
bench-evm = ["revive-differential"]
bench-extensive = []

[dependencies]
hex = { workspace = true }
polkavm = { workspace = true }
revive-integration = { workspace = true }
revive-differential = { workspace = true, optional = true }
alloy-primitives = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "execute"
harness = false

[[bench]]
name = "prepare"
harness = false
